### ISSUE TITLE
UniqueConstraint with InlinePanel

### ISSUE THREAD

**Issue by minusf** [wagtail/django-modelcluster#192] opened 2024-10-14 12:38 UTC
### Issue Summary

Converting a `unique_together` to `UniqueConstraint` results in an uncaught `IntegrityError` when trying to add a duplicate in a related model with `InlinePanel`.

```py
    class Meta:
        # uncaught IntegrityError
        constraints = (
            models.UniqueConstraint(fields=["short_name", "meeting_site"], name="unique_room"),
        )
        # this works
        unique_together = ("short_name", "meeting_site")
```

I found this older issue relating to `unique_together`: https://github.com/wagtail/wagtail/issues/2136

I also found this issue, but it seems it's only for images? https://github.com/wagtail/wagtail/issues/8715

### Technical details

-   Python version: `Python 3.12.7`
-   Django version: `5.1.2`
-   Wagtail version: `6.2.2`
-   Browser version: `FF 131.0.2`

**Comment by minusf** [comment] 2024-11-08 14:40
Do you need me to do anything else?  Will this be part of the package?

**Comment by laymonage** [comment] 2024-12-05 10:29
I've made a PR #194 that's awaiting review – I just realised this is likely a duplicate of #189, so I'll close this in favour of that one.

**Closed by laymonage** 2024-12-05 10:29 UTC
Labels: bug
